using System.Globalization;

namespace DailyQuest.Localization;

public sealed record UiCopy
{
    public required CultureInfo Culture { get; init; }

    public string WindowTitle { get; init; } = "Daily Quest";
    public string TodayTab { get; init; } = "Hari ini";
    public string HistoryTab { get; init; } = "Riwayat";
    public string UpcomingTab { get; init; } = "Mendatang";
    public string SettingsTab { get; init; } = "Pengaturan";
    public string PinWidgetAutomation { get; init; } = "Sematkan widget";
    public string PinOffTooltip { get; init; } = "Lepas dari paling depan";
    public string PinOnTooltip { get; init; } = "Selalu tampil paling depan";
    public string CompactMode { get; init; } = "Mode ringkas";
    public string ExpandMode { get; init; } = "Kembali ke tampilan lengkap";
    public string Minimize { get; init; } = "Minimalkan";
    public string Close { get; init; } = "Tutup";
    public string DeleteActivity { get; init; } = "Hapus aktivitas";
    public string ReorderActivity { get; init; } = "Tarik untuk mengubah urutan";
    public string CompactAllDone { get; init; } = "Semua quest selesai";
    public string EmptyTitle { get; init; } = "Daftar masih kosong";
    public string EmptyHint { get; init; } = "Tambahkan satu kebiasaan kecil di bawah.";
    public string NewItemTooltip { get; init; } = "Ketik aktivitas baru, lalu tekan Enter";
    public string NewItemPlaceholder { get; init; } = "Tambah aktivitas...";
    public string AddActivity { get; init; } = "Tambah aktivitas";
    public string DurationPickerTitle { get; init; } = "Waktu pengerjaan";
    public string NoTimer { get; init; } = "Tanpa timer";
    public string DurationMinutesFormat { get; init; } = "{0} mnt";
    public string DurationMinuteSuffix { get; init; } = "mnt";
    public string CustomDuration { get; init; } = "Durasi lain";
    public string CustomDurationHint { get; init; } = "1-480 menit";
    public string ApplyDuration { get; init; } = "Terapkan";
    public string StartTimer { get; init; } = "Mulai timer";
    public string PauseTimer { get; init; } = "Jeda timer";
    public string ResumeTimer { get; init; } = "Lanjutkan timer";
    public string ToggleTimer { get; init; } = "Mulai atau jeda timer";
    public string ResetTimer { get; init; } = "Reset timer";
    public string StartOvertime { get; init; } = "Mulai overtime";
    public string OvertimeButton { get; init; } = "Overtime";
    public string OvertimeSetting { get; init; } = "Mode overtime";
    public string OvertimeHint { get; init; } = "Izinkan timer terus menghitung setelah waktu habis. Tombol overtime mematikan alarm lalu melanjutkan timer dalam warna merah.";
    public string OvertimeOff { get; init; } = "Nonaktif";
    public string OvertimeOn { get; init; } = "Aktif";
    public string LabelPickerTitle { get; init; } = "Pilih label";
    public string NoLabel { get; init; } = "Tanpa label";
    public string ManageLabels { get; init; } = "Atur label";
    public string ChangeQuestLabel { get; init; } = "Ubah label quest";
    public string SortQuests { get; init; } = "Urutkan quest";
    public string SortManual { get; init; } = "Manual";
    public string SortLabel { get; init; } = "Label";
    public string SortShortest { get; init; } = "Tercepat";
    public string SortLongest { get; init; } = "Terlama";
    public string ScheduleFor { get; init; } = "Jadwalkan untuk";
    public string ScheduleToday { get; init; } = "Hari ini";
    public string ScheduleTomorrow { get; init; } = "Besok";
    public string ScheduleOffsetFormat { get; init; } = "H+{0}";
    public string ScheduleOptionFormat { get; init; } = "{0} · {1}";
    public string AutoSaveStatus { get; init; } = "Tersimpan · reset harian";
    public string ClearCompleted { get; init; } = "Hapus selesai";
    public string Reset { get; init; } = "Reset";
    public string ResetTooltip { get; init; } = "Kosongkan semua centang hari ini";
    public string MorningGreeting { get; init; } = "Selamat pagi!";
    public string NoonGreeting { get; init; } = "Selamat siang!";
    public string AfternoonGreeting { get; init; } = "Selamat sore!";
    public string EveningGreeting { get; init; } = "Selamat malam!";
    public string ProgressEmpty { get; init; } = "Belum ada aktivitas";
    public string ProgressFormat { get; init; } = "{0} dari {1} selesai";
    public string EncourageEmpty { get; init; } = "Mulai dari satu hal kecil buat pagi ini.";
    public string EncourageDone { get; init; } = "Semua beres. Hari ini punya lo!";
    public string EncourageNone { get; init; } = "Pelan-pelan, mulai dari yang paling gampang.";
    public string EncourageRemainingFormat { get; init; } = "Tinggal {0} lagi. Lanjut!";
    public string HistoryEmptyTitle { get; init; } = "Belum ada riwayat";
    public string HistoryEmptyHint { get; init; } = "Riwayat akan muncul setelah kamu mulai mengisi checklist.";
    public string HistorySummaryFormat { get; init; } = "{0} dari {1} selesai";
    public string UpcomingTitle { get; init; } = "Quest mendatang";
    public string UpcomingHint { get; init; } = "Quest akan masuk ke daftar aktif saat harinya tiba.";
    public string UpcomingEmptyTitle { get; init; } = "Belum ada quest mendatang";
    public string UpcomingEmptyHint { get; init; } = "Pilih Besok sampai H+8 saat menambahkan quest.";
    public string RemoveScheduledQuest { get; init; } = "Hapus quest terjadwal";
    public string UpcomingDateFormat { get; init; } = "ddd, d MMM";
    public string SettingsTitle { get; init; } = "Pengaturan";
    public string SettingsSubtitle { get; init; } = "Atur pengalaman Daily Quest sesuai kebutuhanmu.";
    public string LanguageSetting { get; init; } = "Bahasa";
    public string IndonesianLanguage { get; init; } = "Bahasa Indonesia";
    public string EnglishLanguage { get; init; } = "English";
    public string AppearanceSetting { get; init; } = "Tampilan";
    public string AppearanceHint { get; init; } = "Pilih tema yang paling nyaman dilihat.";
    public string LightTheme { get; init; } = "Terang";
    public string DarkTheme { get; init; } = "Gelap";
    public string WindowSizeSetting { get; init; } = "Ukuran jendela";
    public string WindowSizeHint { get; init; } = "Tarik tepi jendela untuk mengatur ukuran sesuai kebutuhan.";
    public string ResetWindowSize { get; init; } = "Reset ukuran";
    public string LabelSettingsTitle { get; init; } = "Label quest";
    public string LabelSettingsHint { get; init; } = "Atur nama, warna, dan prioritas label untuk quest-mu.";
    public string LabelLimitFormat { get; init; } = "{0} dari {1} label";
    public string LabelName { get; init; } = "Nama label";
    public string LabelColor { get; init; } = "Warna #RRGGBB";
    public string PickLabelColor { get; init; } = "Pilih warna label";
    public string AddLabel { get; init; } = "Tambah label";
    public string SaveLabel { get; init; } = "Simpan perubahan label";
    public string DeleteLabel { get; init; } = "Hapus label";
    public string MoveLabelUp { get; init; } = "Naikkan prioritas label";
    public string MoveLabelDown { get; init; } = "Turunkan prioritas label";
    public string InvalidLabel { get; init; } = "Gunakan nama unik dan warna dengan format #RRGGBB.";
    public string DeleteLabelConfirmTitle { get; init; } = "Hapus label ini?";
    public string DeleteLabelConfirmMessage { get; init; } = "Label akan dilepas dari quest aktif, terjadwal, dan riwayat. Quest tidak akan dihapus.";
    public string StorageTitle { get; init; } = "Penyimpanan";
    public string ApplicationStorage { get; init; } = "Aplikasi";
    public string DataStorage { get; init; } = "Data tersimpan";
    public string HistoryStorage { get; init; } = "Riwayat";
    public string StorageHint { get; init; } = "Data tersimpan hanya di perangkat ini.";
    public string ClearHistory { get; init; } = "Hapus riwayat";
    public string ClearHistoryHint { get; init; } = "Menghapus riwayat tanpa menghapus quest aktif atau terjadwal.";
    public string ClearHistoryConfirmTitle { get; init; } = "Hapus seluruh riwayat?";
    public string ClearHistoryConfirmMessage { get; init; } = "Semua catatan riwayat akan dihapus permanen. Quest aktif dan mendatang tetap aman.";
    public string HelpTitle { get; init; } = "Bantuan";
    public string Qna { get; init; } = "Q&A";
    public string QnaHint { get; init; } = "Jawaban singkat untuk pertanyaan umum.";
    public string ReportBug { get; init; } = "Laporkan bug";
    public string ReportBugHint { get; init; } = "Buka formulir GitHub Issue untuk melaporkan masalah.";
    public string FooterFormat { get; init; } = "Daily Quest · v{0}";
    public string SettingsFooter { get; init; } = "Dibuat untuk membantu satu quest kecil pada satu waktu.";
}

public static class UiCopyCatalog
{
    public const string IndonesianCode = "id-ID";
    public const string EnglishCode = "en-US";

    public static UiCopy Indonesian { get; } = new()
    {
        Culture = CultureInfo.GetCultureInfo(IndonesianCode)
    };

    public static UiCopy English { get; } = new()
    {
        Culture = CultureInfo.GetCultureInfo(EnglishCode),
        TodayTab = "Today",
        HistoryTab = "History",
        UpcomingTab = "Upcoming",
        SettingsTab = "Settings",
        PinWidgetAutomation = "Pin widget",
        PinOffTooltip = "Turn off always on top",
        PinOnTooltip = "Always on top",
        CompactMode = "Compact mode",
        ExpandMode = "Return to full view",
        Minimize = "Minimize",
        Close = "Close",
        DeleteActivity = "Delete activity",
        ReorderActivity = "Drag to change order",
        CompactAllDone = "All quests complete",
        EmptyTitle = "Your list is empty",
        EmptyHint = "Add one small habit below.",
        NewItemTooltip = "Type a new activity, then press Enter",
        NewItemPlaceholder = "Add an activity...",
        AddActivity = "Add activity",
        DurationPickerTitle = "Time needed",
        NoTimer = "No timer",
        DurationMinutesFormat = "{0} min",
        DurationMinuteSuffix = "min",
        CustomDuration = "Custom duration",
        CustomDurationHint = "1-480 minutes",
        ApplyDuration = "Apply",
        StartTimer = "Start timer",
        PauseTimer = "Pause timer",
        ResumeTimer = "Resume timer",
        ToggleTimer = "Start or pause timer",
        ResetTimer = "Reset timer",
        StartOvertime = "Start overtime",
        OvertimeButton = "Overtime",
        OvertimeSetting = "Overtime mode",
        OvertimeHint = "Allow a timer to keep counting after time runs out. The overtime button silences the alarm and continues the timer in red.",
        OvertimeOff = "Off",
        OvertimeOn = "On",
        LabelPickerTitle = "Choose a label",
        NoLabel = "No label",
        ManageLabels = "Manage labels",
        ChangeQuestLabel = "Change quest label",
        SortQuests = "Sort quests",
        SortManual = "Manual",
        SortLabel = "Label",
        SortShortest = "Shortest",
        SortLongest = "Longest",
        ScheduleFor = "Schedule for",
        ScheduleToday = "Today",
        ScheduleTomorrow = "Tomorrow",
        ScheduleOffsetFormat = "D+{0}",
        ScheduleOptionFormat = "{0} · {1}",
        AutoSaveStatus = "Autosaved · daily reset",
        ClearCompleted = "Clear done",
        Reset = "Reset",
        ResetTooltip = "Uncheck everything for today",
        MorningGreeting = "Good morning!",
        NoonGreeting = "Good afternoon!",
        AfternoonGreeting = "Good evening!",
        EveningGreeting = "Good evening!",
        ProgressEmpty = "No activities yet",
        ProgressFormat = "{0} of {1} done",
        EncourageEmpty = "Start with one small thing this morning.",
        EncourageDone = "All done. Today is yours!",
        EncourageNone = "Take it easy—start with the simplest one.",
        EncourageRemainingFormat = "{0} left. Keep going!",
        HistoryEmptyTitle = "No history yet",
        HistoryEmptyHint = "History will appear after you start using the checklist.",
        HistorySummaryFormat = "{0} of {1} done",
        UpcomingTitle = "Upcoming quests",
        UpcomingHint = "A quest moves into your active list when its day arrives.",
        UpcomingEmptyTitle = "No upcoming quests",
        UpcomingEmptyHint = "Choose Tomorrow through D+8 when adding a quest.",
        RemoveScheduledQuest = "Remove scheduled quest",
        UpcomingDateFormat = "ddd, MMM d",
        SettingsTitle = "Settings",
        SettingsSubtitle = "Shape Daily Quest around the way you work.",
        LanguageSetting = "Language",
        IndonesianLanguage = "Indonesian",
        EnglishLanguage = "English",
        AppearanceSetting = "Appearance",
        AppearanceHint = "Choose the theme that feels best to you.",
        LightTheme = "Light",
        DarkTheme = "Dark",
        WindowSizeSetting = "Window size",
        WindowSizeHint = "Drag any window edge to adjust the size to your workspace.",
        ResetWindowSize = "Reset size",
        LabelSettingsTitle = "Quest labels",
        LabelSettingsHint = "Customize label names, colors, and priority order for your quests.",
        LabelLimitFormat = "{0} of {1} labels",
        LabelName = "Label name",
        LabelColor = "Color #RRGGBB",
        PickLabelColor = "Choose label color",
        AddLabel = "Add label",
        SaveLabel = "Save label changes",
        DeleteLabel = "Delete label",
        MoveLabelUp = "Move label up",
        MoveLabelDown = "Move label down",
        InvalidLabel = "Use a unique name and a color in #RRGGBB format.",
        DeleteLabelConfirmTitle = "Delete this label?",
        DeleteLabelConfirmMessage = "The label will be removed from active, scheduled, and historical quests. No quest will be deleted.",
        StorageTitle = "Storage",
        ApplicationStorage = "Application",
        DataStorage = "Saved data",
        HistoryStorage = "History",
        StorageHint = "Saved data stays only on this device.",
        ClearHistory = "Clear history",
        ClearHistoryHint = "Deletes history without removing active or scheduled quests.",
        ClearHistoryConfirmTitle = "Clear all history?",
        ClearHistoryConfirmMessage = "Every history record will be permanently removed. Active and upcoming quests will stay safe.",
        HelpTitle = "Help",
        Qna = "Q&A",
        QnaHint = "Quick answers to common questions.",
        ReportBug = "Report a bug",
        ReportBugHint = "Open a GitHub Issue form to report a problem.",
        FooterFormat = "Daily Quest · v{0}",
        SettingsFooter = "Made to help with one small quest at a time."
    };

    public static string NormalizeLanguageCode(string? code) => code?.Trim().ToLowerInvariant() switch
    {
        "en" or "en-us" => EnglishCode,
        "id" or "id-id" => IndonesianCode,
        _ => EnglishCode
    };

    public static UiCopy For(string? code) =>
        NormalizeLanguageCode(code) == EnglishCode ? English : Indonesian;
}
